import os
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart


def send_routine_email(
    to_email: str,
    user_name: str,
    routine_json: dict
) -> bool:

    subject = "Your Personalized Skincare Routine 💙"

    def format_steps(steps):
        if not steps:
            return "No specific steps provided."
        return "\n".join(
            [
                f"{s.get('step', '-')}. {s.get('productType', 'Product')} – {s.get('instructions', '')}"
                for s in steps
            ]
        )

    body = f"""
Hi {user_name},

Here is your personalized skincare routine generated by Saundarya Ai 🌸

🌞 MORNING:
{format_steps(routine_json.get("morning", []))}

🌙 EVENING:
{format_steps(routine_json.get("evening", []))}

📅 WEEKLY CARE:
{format_steps(routine_json.get("weekly", []))}

📝 Summary:
{routine_json.get("summary", "No summary available.")}

Stay consistent & glow ✨  
– Saundarya AI
"""

    try:
        msg = MIMEMultipart()
        msg["From"] = os.getenv("FROM_EMAIL")
        msg["To"] = to_email
        msg["Subject"] = subject
        msg.attach(MIMEText(body, "plain"))

        smtp_host = os.getenv("SMTP_HOST")
        smtp_port = int(os.getenv("SMTP_PORT", 587))

        with smtplib.SMTP(smtp_host, smtp_port) as server:
            server.starttls()
            server.login(
                os.getenv("SMTP_USER"),
                os.getenv("SMTP_PASSWORD")
            )
            server.send_message(msg)

        return True

    except Exception as e:
        print("Email sending failed:", str(e))
        return False
